server:
  port: 8082

spring:
  datasource:
    url: jdbc:oracle:thin:@${INVESTMENT_DB_HOST:localhost}:${INVESTMENT_DB_PORT:1521}/${INVESTMENT_DB_NAME:FREEPDB1}
    username: ${INVESTMENT_DB_USER:vankoo_investment}
    password: ${INVESTMENT_DB_PASSWORD:vankoo_password}
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST:localhost}:${KAFKA_EXTERNAL_PORT:9092}
          auto-create-topics: true
          producer-properties:
            acks: all
            retries: 3
            enable.idempotence: true
      bindings:
        processInvoicingOcrEvent-in-0:
          destination: invoicing.invoice-ocr-processed
          group: investment-service-group
          content-type: application/json

eureka:
  instance:
    prefer-ip-address: false
  client:
    enabled: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
       include: "health,info"